version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: ganadoapp-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ganado_admin
      MONGO_INITDB_ROOT_PASSWORD: change_me_password
      MONGO_INITDB_DATABASE: ganadodb
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    name: ganadoapp-mongo-data
